class ClusteringError(Exception):
    """Исключение, возникающее при ошибках кластеризации"""

    pass
